#!/usr/bin/env bash
# Start a local dc-agent on :8051 with a minimal test config, in the background.
# Boots with no Docker/daemontools: /health + /app-status + control-plane service
# list work; /docker/check needs the generated api-keys file + a writable TEMP_DIR
# (both provided here under .run/).
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

resolve_java
[[ -f "$AGENT_JAR" ]] || die "agent jar not built: $AGENT_JAR — run: verify/build-backend.sh"

mkdir -p "$LOG_DIR" "$PID_DIR" "$AGENT_SERVICES_DIR" "$AGENT_SERVICES_DEF_DIR" "$AGENT_SERVICES_LOG_DIR" "$AGENT_TMP_DIR"

# Rebuild the agent CONFIG_DIR: example command configs (shown in the Command list)
# + a generated dc-docker.yml (api-keys for /docker/*, excluded from the command list).
rm -rf "$AGENT_CONFIG_DIR"
mkdir -p "$AGENT_CONFIG_DIR"
cp "$AGENT_CONFIG_TEMPLATE_DIR"/*.yml "$AGENT_CONFIG_DIR"/

# Agent api-keys file: the key must equal the operator's per-agent `token`.
cat > "$AGENT_CONFIG_DIR/dc-docker.yml" <<YAML
# Generated by verify/run-agent.sh — validates the operator's api-key on /docker/*.
type: DOCKER
apiKeys:
  ${AGENT_API_KEY}: local-operator
YAML

# Populate daemontools service dirs so the Service list is non-empty.
"$VERIFY_DIR/setup-services.sh"

# Write the IDEA env files, then launch from the agent one (single source of truth).
"$VERIFY_DIR/write-idea-env.sh"

log "Starting dc-agent on :$AGENT_PORT ..."
set -a; source "$AGENT_ENV_FILE"; set +a
nohup "$JAVA" -jar "$AGENT_JAR" > "$LOG_DIR/agent.log" 2>&1 &
echo $! > "$PID_DIR/agent.pid"

wait_http "$AGENT_BASE/health" "dc-agent"
