#!/usr/bin/env bash
# Materialize the operator's config as a real git repo so /git/log, /git/status and
# /git/pull work and dc-operator reads its apps/tasks from git. A local bare "origin" is
# created so `verify/add-commit.sh` can push a commit the UI's Pull then fetches (needs the
# operator built with the local-pull fix; see verify/README.md). Idempotent: rebuilds it.
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

log "Materializing config git repo at $CONFIG_DIR"
rm -rf "$CONFIG_DIR" "$CONFIG_REMOTE"
mkdir -p "$RUN_DIR"

# Working checkout = apps/ + tasks/ from the template + a generated agent fleet file.
mkdir -p "$CONFIG_DIR"
cp -R "$CONFIG_TEMPLATE_DIR/apps" "$CONFIG_DIR/apps"
cp -R "$CONFIG_TEMPLATE_DIR/tasks" "$CONFIG_DIR/tasks"

# operator-config.yaml is generated (not committed) so its tokens always match the
# local dc-agent started by run-agent.sh, and no secrets live in the repo.
cat > "$CONFIG_DIR/operator-config.yaml" <<YAML
# Generated by verify/setup-config.sh — local test fleet (one local agent).
# Per-agent tokens MUST equal the local dc-agent's (see verify/lib.sh).
agents:
  - name           : local
    url            : ${AGENT_BASE}
    token          : ${AGENT_API_KEY}
    cpToken        : ${CP_TOKEN}
    appStatusToken : ${APP_STATUS_TOKEN}
YAML

# Bare remote first, then commit + push so the checkout has an 'origin' to pull from.
git init -q --bare "$CONFIG_REMOTE"
git -C "$CONFIG_DIR" init -q -b main
git -C "$CONFIG_DIR" -c user.email=verify@local -c user.name=verify add -A
git -C "$CONFIG_DIR" -c user.email=verify@local -c user.name=verify commit -q -m "Local verify config: hello-local app + local agent"
git -C "$CONFIG_DIR" remote add origin "$CONFIG_REMOTE"
git -C "$CONFIG_DIR" push -q -u origin main

log "Config repo ready:"
log "  REPO_DIR = $CONFIG_DIR"
log "  origin   = $CONFIG_REMOTE  (add demo commits with verify/add-commit.sh)"
