#!/usr/bin/env bash
# Write .env files (IntelliJ IDEA "EnvFile" plugin format) for dc-agent and dc-operator into
# .run/, so you can run/debug them straight from the IDE with the same environment the harness
# uses. These same files are sourced by run-agent.sh / run-operator.sh to launch, so the harness
# and the IDE stay in sync. (Values are absolute, space-free, so they parse identically in the
# EnvFile plugin and via bash `source`.)
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

mkdir -p "$RUN_DIR"

cat > "$AGENT_ENV_FILE" <<ENV
# dc-agent — IDEA: run 'com.payneteasy.dcagent.DcAgentApplication' with this file via the
# EnvFile plugin. Generated by verify/write-idea-env.sh (regenerated on each run-agent.sh).
CONFIG_DIR=$AGENT_CONFIG_DIR
WEB_SERVER_PORT=$AGENT_PORT
WEB_SERVER_CONTEXT=/dc-agent
CONTROL_PLANE_ENABLED=true
CONTROL_PLANE_TOKEN=$CP_TOKEN
APP_STATUS_TOKEN=$APP_STATUS_TOKEN
APP_INSTANCE_NAME=dc-agent-local
TEMP_DIR=$AGENT_TMP_DIR
SERVICES_DIR=$AGENT_SERVICES_DIR
SERVICES_DEFINITION_DIR=$AGENT_SERVICES_DEF_DIR
SERVICES_LOG_DIR=$AGENT_SERVICES_LOG_DIR
DAEMONTOOLS_SVC_PATH=$VERIFY_DIR/bin/svc
ENV

cat > "$OPERATOR_ENV_FILE" <<ENV
# dc-operator — IDEA: run 'com.payneteasy.dcagent.operator.DcAgentOperatorApplication' with this
# file via the EnvFile plugin. Generated by verify/write-idea-env.sh (regenerated on run-operator.sh).
JETTY_PORT=$OPERATOR_PORT
JETTY_CONTEXT=/dc-operator
REPO_DIR=$CONFIG_DIR
CONFIG_FILE=$CONFIG_DIR/operator-config.yaml
REPO_APPS_RELATIVE_DIR=apps
REPO_TASKS_RELATIVE_DIR=tasks
GIT_FETCH_REPO_ON_STARTUP=true
ENV

log "Wrote IDEA env files:"
log "  agent    : $AGENT_ENV_FILE   (main: com.payneteasy.dcagent.DcAgentApplication)"
log "  operator : $OPERATOR_ENV_FILE   (main: com.payneteasy.dcagent.operator.DcAgentOperatorApplication)"
